mysite/api/urls.py
from django.urls import path

from .views import CityListView

app_name = "api"

urlpatterns = [
    path("city-count/", CityListView.as_view(), name="city_count"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("weather/", include("weather.urls")),
    path("api/", include("api.urls")),
]

mysite/weather/urls.py
from django.urls import path

from .views import city_form, get_weather_for_city, get_weather_from_history

app_name = "weather"

urlpatterns = [
    path("city/", city_form, name="search_city"),
    path("result/", get_weather_for_city, name="result"),
    path(
        "history-result/<int:index>/", get_weather_from_history, name="history_result"
    ),
]

mysite/api/models.py
from django.db import models

# Create your models here.

mysite/weather/models.py
from django.db import models


class City(models.Model):
    """Город"""

    name = models.CharField(verbose_name="Название города", unique=True, max_length=150)
    count = models.IntegerField(
        verbose_name="Сколько раз искали этот город", blank=True, null=False, default=1
    )

    def __str__(self):
        return self.name

mysite/weather/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


def validate_city(location: str) -> None:
    """Валидатор для обработки названия города"""
    if not location.isalpha():
        raise ValidationError(
            _(f"Локация должна содержать только буквы"), params={"location": location}
        )


class SearchCity(forms.Form):
    """Форма для ввода города"""

    city = forms.CharField(label="Название города", validators=[validate_city])

mysite/api/views.py
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from weather.models import City


class CityListView(APIView):
    def get(self, request: Request) -> Response:
        """Получение списка всех введённых локаций"""
        locations = City.objects.all()
        data = {loc.name: loc.count for loc in locations}
        return Response({"locations": data})

mysite/weather/views.py
from django.core.exceptions import BadRequest
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import SearchCity
from .utils import prepare_weather_data, update_search_history


def city_form(request: HttpRequest) -> HttpResponse:
    """Ввод локации для получения прогноза погоды"""
    search_history = request.session.get("search_history", [])
    if request.method == "POST":
        form = SearchCity(request.POST)
        if form.is_valid():
            location = form.cleaned_data.get("city")
            try:
                weather_data, hourly_data = prepare_weather_data(location)
            except BadRequest as e:
                form.add_error("city", str(e))
            else:
                request.session["weather_data"] = weather_data
                request.session["hourly"] = hourly_data
                request.session["location"] = location
                update_search_history(
                    request.session, location, weather_data, hourly_data
                )
                return redirect(reverse("weather:result"))
    else:
        form = SearchCity()
    return render(
        request,
        "weather/city-index.html",
        context={"form": form, "search_history": search_history},
    )


def get_weather_for_city(request: HttpRequest) -> HttpResponse:
    """Получение погоды для введённой локации"""
    weather_data = request.session.get("weather_data")
    hourly = request.session.get("hourly")
    location = request.session.get("location")
    context = {
        "weather_data": weather_data,
        "hourly": hourly,
        "location": location,
    }
    return render(request, "weather/result.html", context=context)


def get_weather_from_history(request: HttpRequest, index: int) -> HttpResponse:
    """
    Достаёт прогноз погоды из истории поиска
    :param request: HttpRequest
    :param index: int - индекс локации из request.session["search_history]
    :return: HttpResponse
    """
    search_history = request.session.get("search_history", [])
    if index < 0 or index >= len(search_history):
        raise Http404("Элемент истории не найден")
    location = search_history[index]
    context = {
        "weather_data": location["weather_data"],
        "hourly": location["hourly"],
        "location": location["location"],
    }

    return render(request, "weather/result.html", context=context)

mysite/weather/templates/weather/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock %}
</body>

<footer>
    <div>
        {% load tz %}

        {% timezone "Europe/Moscow" %}
            {% now "H:i" %}
        {% endtimezone %}
    </div>

    <div>
        {% now 'l' as current_weekday %}
        Today is {{ current_weekday }}
    </div>
</footer>
</html>

mysite/weather/templates/weather/city-index.html
{% extends 'weather/base.html' %}


{% block body %}
<h1>Поиск локации</h1>
<div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit">
            Поиск
        </button>
    </form>
</div>

{% if search_history %}
<div>
    <h2>История поиска</h2>
    <ul>
        {% for loc in search_history %}
        <a href="{% url 'weather:history_result' forloop.counter0 %}">
            <li>{{ loc.location }}</li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endblock %}

mysite/weather/templates/weather/result.html
{% extends 'weather/base.html' %}

{% block title %}
    Погода
{% endblock %}

{% block body %}
<h2>{{ location }}</h2>
<p>Координаты: {{ weather_data.Coordinates.latitude }}°N  {{ weather_data.Coordinates.longitude }}°E</p>
<p>Часовой пояс: {{ weather_data.Timezone }}</p>
<p>Высота над уровнем моря: {{ weather_data.Elevation }} м</p>
<p>Разница времени GMT+0: {{ weather_data.Timezone_diff_GMT_0 }} сек</p>

<h3>Прогноз по дням</h3>

{% regroup hourly by date|slice:":10" as daily_forecast %}

{% for day in daily_forecast %}
    <h4>{{ day.grouper }}</h4>
    <table>
        <thead>
            <tr>
                <th>Время</th>
                <th>Температура (°C)</th>
                <th>Ощущается как (°C)</th>
                <th>Ветер м/с</th>
                <th>Дождь (мм)</th>
            </tr>
        </thead>
        <tbody>
        {% for row in day.list %}
            <tr>
                <td>{{ row.date|slice:"11:16" }}</td>
                <td>{{ row.temperature_2m }}</td>
                <td>{{ row.apparent_temperature }}</td>
                <td>{{ row.wind_speed_10m }}</td>
                <td>{{ row.rain }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endfor %}
{% endblock %}

mysite/weather/templates/weather/weather-index.html
{% extends 'weather/base.html' %}

{% block body %}
  <h1>Hello from weather</h1>
{% endblock %}